name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: where are we
      run: pwd
    - name: list some key files
      run: ls -lrt
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./StudioSolunaWebPortfolio
    - name: Build
      run: dotnet build --no-restore
      working-directory: ./StudioSolunaWebPortfolio
    
